// Code generated by "stringer -type=MessageType -output=types_strings.go"; DO NOT EDIT.

package prdemo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerDetailsType-0]
	_ = x[DodListType-1]
	_ = x[PlayerUpdateType-16]
	_ = x[PlayerAddType-17]
	_ = x[PlayerRemoveType-18]
	_ = x[VehicleUpdateType-32]
	_ = x[VehicleAddType-33]
	_ = x[VehicleDestroyedType-34]
	_ = x[FobAddType-48]
	_ = x[FobRemoveType-49]
	_ = x[FlagUpdateType-64]
	_ = x[FlagListType-65]
	_ = x[KillType-80]
	_ = x[ChatType-81]
	_ = x[TicketsTeam1Type-82]
	_ = x[TicketsTeam2Type-83]
	_ = x[RallyAddType-96]
	_ = x[RallyRemoveType-97]
	_ = x[CacheAddType-112]
	_ = x[CacheRemoveType-113]
	_ = x[CacheRevealType-114]
	_ = x[IntelChangeType-115]
	_ = x[MarkerAddType-128]
	_ = x[MarkerRemoveType-129]
	_ = x[ProjUpdateType-144]
	_ = x[ProjAddType-145]
	_ = x[ProjRemoveType-146]
	_ = x[ReviveType-160]
	_ = x[KitAllocatedType-161]
	_ = x[SquadNameType-162]
	_ = x[SlOrdersType-163]
	_ = x[RoundEndType-240]
	_ = x[TicksType-241]
	_ = x[PrivateMessageType-253]
	_ = x[ErrorMessageType-254]
}

const _MessageType_name = "ServerDetailsTypeDodListTypePlayerUpdateTypePlayerAddTypePlayerRemoveTypeVehicleUpdateTypeVehicleAddTypeVehicleDestroyedTypeFobAddTypeFobRemoveTypeFlagUpdateTypeFlagListTypeKillTypeChatTypeTicketsTeam1TypeTicketsTeam2TypeRallyAddTypeRallyRemoveTypeCacheAddTypeCacheRemoveTypeCacheRevealTypeIntelChangeTypeMarkerAddTypeMarkerRemoveTypeProjUpdateTypeProjAddTypeProjRemoveTypeReviveTypeKitAllocatedTypeSquadNameTypeSlOrdersTypeRoundEndTypeTicksTypePrivateMessageTypeErrorMessageType"

var _MessageType_map = map[MessageType]string{
	0:   _MessageType_name[0:17],
	1:   _MessageType_name[17:28],
	16:  _MessageType_name[28:44],
	17:  _MessageType_name[44:57],
	18:  _MessageType_name[57:73],
	32:  _MessageType_name[73:90],
	33:  _MessageType_name[90:104],
	34:  _MessageType_name[104:124],
	48:  _MessageType_name[124:134],
	49:  _MessageType_name[134:147],
	64:  _MessageType_name[147:161],
	65:  _MessageType_name[161:173],
	80:  _MessageType_name[173:181],
	81:  _MessageType_name[181:189],
	82:  _MessageType_name[189:205],
	83:  _MessageType_name[205:221],
	96:  _MessageType_name[221:233],
	97:  _MessageType_name[233:248],
	112: _MessageType_name[248:260],
	113: _MessageType_name[260:275],
	114: _MessageType_name[275:290],
	115: _MessageType_name[290:305],
	128: _MessageType_name[305:318],
	129: _MessageType_name[318:334],
	144: _MessageType_name[334:348],
	145: _MessageType_name[348:359],
	146: _MessageType_name[359:373],
	160: _MessageType_name[373:383],
	161: _MessageType_name[383:399],
	162: _MessageType_name[399:412],
	163: _MessageType_name[412:424],
	240: _MessageType_name[424:436],
	241: _MessageType_name[436:445],
	253: _MessageType_name[445:463],
	254: _MessageType_name[463:479],
}

func (i MessageType) String() string {
	if str, ok := _MessageType_map[i]; ok {
		return str
	}
	return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
}
