// Code generated by "stringer -type=Layer -linecomment -output=messages_strings.go"; DO NOT EDIT.

package prism2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LayerUnknown-0]
	_ = x[LayerInfantry-16]
	_ = x[LayerAlternative-32]
	_ = x[LayerStandard-64]
	_ = x[LayerLarge-128]
}

const (
	_Layer_name_0 = "???"
	_Layer_name_1 = "inf"
	_Layer_name_2 = "alt"
	_Layer_name_3 = "std"
	_Layer_name_4 = "lrg"
)

func (i Layer) String() string {
	switch {
	case i == 0:
		return _Layer_name_0
	case i == 16:
		return _Layer_name_1
	case i == 32:
		return _Layer_name_2
	case i == 64:
		return _Layer_name_3
	case i == 128:
		return _Layer_name_4
	default:
		return "Layer(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
